print('Hello, world')
print('enrolados')
print('a princesa e o sapo')
print('moana')
print('mulan')
print('encanto')
print('luca')
print('viagem de chihiro')
print('meu amigo totoro')
print('ponyo')
